name: Build

on:
  # manual trigger
  workflow_dispatch:
    branches: [main, lint-change-one]

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

  build:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image one
      working-directory: ./apps/docker-node-example
      run: |
        docker build . -t docker-node-example-latest
    - name: Build Docker image two
      working-directory: ./apps/docker-rails-example
      run: |
        docker build . -t docker-rails-example-latest
