name: Build

on:
  # manual trigger
  workflow_dispatch:
    branches: [main]
jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - 
      name: set-matrix
      id: set-matrix
      run: |
        sudo apt-get install jq
        echo "::set-output name=matrix::$(bash bin/get-docker-contexts.sh)"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build:
    runs-on: ubuntu-latest
    needs: pre-build
    strategy:
      matrix:
        dockercontext: ${{fromJson(needs.pre-build.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build Docker image 
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.dockercontext }}
        push: false
        tags: docker-node-example:latest
