name: Build

on:
  # manual trigger
  workflow_dispatch:
    branches: [main]
jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

  build:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
    - uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build Docker image one
      id: docker_build_one
      uses: docker/build-push-action@v2
      with:
        context: ./apps/docker-node-example
        push: false
        tags: docker-node-example:latest
    -
      name: Build Docker image two
      id: docker_build_two
      uses: docker/build-push-action@v2
      with:
        context: ./apps/docker-rails-example
        push: false
        tags: docker-rails-example:latest    
