name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
    - 'documentation/**'

jobs:
  deploy:
    name: build docker image and deploy
    runs-on: ubuntu-20.04
    steps:
    - uses: DFE-Digital/github-actions/turnstyle@master
      name: Check workflow concurrency
      with:
        initial-wait-seconds: 20
        poll-interval-seconds: 20
        same-branch-only: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      name: Checkout Code

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        tags: user/app:latest

    - name: Trigger Smoke Test
      uses: benc-uk/workflow-dispatch@v1.1
      with:
        workflow: Smoke Test Dispatch # Workflow name
        token: ${{ secrets.PERSONAL_TOKEN }}
        inputs: '{"sha": "${{ github.sha }}", "url": "https://nickromney.co"}'

    - name: Wait for smoke test
      id: wait_for_smoke_test
      uses: fountainhead/action-wait-for-check@v1.0.0
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        checkName: Smoke Test SHA ${{ github.sha }} for URL https://nickromney.co # Job name within workflow
        ref: ${{ github.ref }}
        timeoutSeconds: 300
        intervalSeconds: 15

    - name: Fail whole workflow if smoke test not successful
      if: steps.wait_for_smoke_test.outputs.conclusion != 'success'
      shell: bash
      run: exit 1

    - name: Install TF - should be skipped over if first test not successful
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.9
