name: Smoke Test Dispatch

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to test'
        required: true
        default: 'https://nickromney.com'

jobs:
  smoke-test-dispatch-job:
    name: Smoke Test ${{ github.event.inputs.url }}

    runs-on: ubuntu-20.04

    steps:
    - name: Set up smoke.sh
      shell: bash
      run: |
        . bin/smoke.sh
        smoke_url_ok ${{ github.event.inputs.url }}
